apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kbmicro-persistent-volume-claim
  labels:
    app: kbmicro-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi